// Data source: wearedistributed.org's server-rendered HTML (Webflow CMS + Finsweet
// filters - plain semantic HTML, not React streaming; see ../url-reference.md).
// Search has no server-side query/pagination param - the LatAm region page is a
// static, fully pre-rendered ~64-card list, so `search` fetches it once and filters
// client-side. Detail parses a schema.org JobPosting JSON-LD block plus the real
// description HTML (the JSON-LD's own `description` field is useless - just the
// title repeated - confirmed live).

export const BASE = "https://wearedistributed.org"
export const LATAM_PAGE = `${BASE}/remote-jobs/latam`

export function writeError(error: string, code: string): void {
  process.stderr.write(JSON.stringify({ error, code }) + "\n")
}

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

/** Fetch raw HTML text with exponential backoff on 429/5xx. Returns null on 404. */
export async function htmlFetch(url: string): Promise<string | null> {
  const maxRetries = 6
  let delay = 500
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    const response = await fetch(url, {
      headers: {
        "User-Agent": UA,
        Accept: "text/html,application/xhtml+xml",
      },
      signal: AbortSignal.timeout(15000),
    })
    if (response.status === 429 || response.status >= 500) {
      if (attempt === maxRetries) {
        throw new Error(`Request failed: ${response.status} ${response.statusText}`)
      }
      const jitter = Math.floor(Math.random() * 500)
      await new Promise((r) => setTimeout(r, delay + jitter))
      delay = Math.min(delay * 2, 8000)
      continue
    }
    if (response.status === 404) return null
    if (!response.ok) {
      throw new Error(`Request failed: ${response.status} ${response.statusText}`)
    }
    return await response.text()
  }
  throw new Error("Request failed after max retries")
}

export interface JobCard {
  id: string
  title: string
  company: string | null
  location: string | null
  date: string | null // always null on search results - see url-reference.md
  url: string
}

export interface JobDetail extends JobCard {
  description: string | null
  employmentType: string | null
  jobLocationType: string | null
  companyUrl: string | null
  applyUrl: string | null
  datePosted: string | null
  validThrough: string | null
}

function numericEntity(cp: number): string {
  return cp >= 0 && cp <= 0x10ffff ? String.fromCodePoint(cp) : ""
}

// Verified live: this site's rich-text descriptions use named typographic entities
// (rsquo/lsquo/rdquo/ldquo/mdash/ndash/hellip) generated by whatever rich-text editor
// authored the postings - not just the handful of structural entities (&amp; etc.)
// the other portal skills' descriptions carry. Decoded here so `detail --format
// plain` never leaks a literal "&rsquo;" into the output.
const NAMED_ENTITIES: Record<string, string> = {
  amp: "&",
  lt: "<",
  gt: ">",
  quot: '"',
  apos: "'",
  nbsp: " ",
  rsquo: "’",
  lsquo: "‘",
  rdquo: "”",
  ldquo: "“",
  mdash: "—",
  ndash: "–",
  hellip: "…",
  trade: "™",
  copy: "©",
  reg: "®",
}

export function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&#x2011;/gi, "-") // non-breaking hyphen -> plain hyphen, not the raw codepoint
    .replace(/&#(\d+);/g, (_, dec) => numericEntity(parseInt(dec, 10)))
    .replace(/&#[xX]([0-9a-fA-F]+);/g, (_, hex) => numericEntity(parseInt(hex, 16)))
    .replace(/&([a-zA-Z]+);/g, (full, name) => NAMED_ENTITIES[name] ?? full)
}

export function cleanDescription(raw: string | null | undefined): string | null {
  if (!raw) return null
  const withBreaks = raw.replace(/<\s*br\s*\/?>/gi, "\n").replace(/<\/(p|li|ul|ol|div|h\d)>/gi, "\n")
  const text = decodeHtmlEntities(withBreaks.replace(/<[^>]+>/g, ""))
    .replace(/[ \t]+/g, " ")
    .replace(/\n{3,}/g, "\n\n")
    .trim()
  return text || null
}

const CARD_ANCHOR = 'class="job-collection-item opp w-dyn-item"'

function firstMatch(text: string, re: RegExp): string | null {
  const m = text.match(re)
  return m ? m[1] : null
}

/** Split raw search-page HTML into one chunk per job card (drops the pre-first-card prefix). */
export function splitJobCards(html: string): string[] {
  return html.split(CARD_ANCHOR).slice(1)
}

/** Parse one job card chunk (see url-reference.md for the anchor table). */
export function parseCard(chunk: string): JobCard | null {
  const slug = firstMatch(chunk, /href="\/job\/([a-z0-9-]+)"/)
  if (!slug) return null

  const title = firstMatch(chunk, /class="job-listing-name"[^>]*>([^<]*)</)
  if (!title) return null // no title -> unparseable, drop rather than emit blank
  const company = firstMatch(chunk, /class="job-company-name"[^>]*>([^<]*)</)
  const location = firstMatch(chunk, /class="text-block-8 panel-location"[^>]*>([^<]*)</)

  return {
    id: slug,
    title: decodeHtmlEntities(title.trim()),
    company: company ? decodeHtmlEntities(company.trim()) : null,
    location: location ? decodeHtmlEntities(location.trim()) : null,
    date: null, // search page has no posting date - see url-reference.md
    url: `${BASE}/job/${slug}`,
  }
}

export interface RawCard extends JobCard {
  salary: string | null
  expiry: string | null
}

/** Same as parseCard but also captures the two bonus fields (salary estimate, expiry). */
export function parseCardFull(chunk: string): RawCard | null {
  const card = parseCard(chunk)
  if (!card) return null
  const salary = firstMatch(chunk, /class="text-block-8 panel-rec-salary[^"]*"[^>]*>([^<]*)</)
  const expiry = firstMatch(chunk, /class="text-block-8 panel-expiry[^"]*"[^>]*>([^<]*)</)
  return {
    ...card,
    salary: salary ? decodeHtmlEntities(salary.trim()) : null,
    expiry: expiry ? decodeHtmlEntities(expiry.trim()) : null,
  }
}

export function parseSearchPage(html: string): RawCard[] {
  return splitJobCards(html)
    .map(parseCardFull)
    .filter((c): c is RawCard => c !== null)
}

interface JsonLdOrganization {
  name?: string
  sameAs?: string
  logo?: string
}

interface JsonLdJobPosting {
  title?: string
  datePosted?: string
  validThrough?: string
  employmentType?: string
  jobLocationType?: string
  hiringOrganization?: JsonLdOrganization
  jobLocation?: { address?: { addressRegion?: string } }
  applicationContact?: { url?: string }
  url?: string
}

/** Extract and parse the schema.org JobPosting <script type="application/ld+json"> block. */
export function parseJobPostingLd(html: string): JsonLdJobPosting | null {
  const m = html.match(/<script type="application\/ld\+json">(.*?)<\/script>/s)
  if (!m) return null
  try {
    const obj = JSON.parse(m[1])
    if (obj && obj["@type"] === "JobPosting") return obj as JsonLdJobPosting
    return null
  } catch {
    return null
  }
}

/**
 * The JSON-LD's own `description` is useless (a copy of the title - confirmed
 * live). The real description lives in `<div class="ja-intro w-richtext">...`,
 * bounded by the next `<div class="flex-item-20 _40-percent">` sibling.
 */
export function extractDescriptionHtml(html: string): string | null {
  const startMarker = 'class="ja-intro w-richtext"'
  const startIdx = html.indexOf(startMarker)
  if (startIdx === -1) return null
  const contentStart = html.indexOf(">", startIdx) + 1
  const endIdx = html.indexOf('<div class="flex-item-20 _40-percent">', contentStart)
  if (endIdx === -1) return null
  return html.slice(contentStart, endIdx)
}

export function toJobDetail(ld: JsonLdJobPosting, slug: string, html: string): JobDetail {
  const url = `${BASE}/job/${slug}`
  return {
    id: slug,
    title: ld.title ? decodeHtmlEntities(ld.title) : "",
    company: ld.hiringOrganization?.name ? decodeHtmlEntities(ld.hiringOrganization.name) : null,
    location: ld.jobLocation?.address?.addressRegion ? decodeHtmlEntities(ld.jobLocation.address.addressRegion) : null,
    date: ld.datePosted ?? null,
    url,
    description: cleanDescription(extractDescriptionHtml(html)),
    employmentType: ld.employmentType ?? null,
    jobLocationType: ld.jobLocationType ?? null,
    companyUrl: ld.hiringOrganization?.sameAs ?? null,
    applyUrl: ld.applicationContact?.url ?? null,
    datePosted: ld.datePosted ?? null,
    validThrough: ld.validThrough ?? null,
  }
}
